src/app/page.tsx
src/components/ThemeToggle.tsx
tailwind.config.cjs

The page will switch between dark/light mode when the toggle button is clicked

Added dark mode toggle functionality

---

.gitignore
src/app/layout.tsx

Config eslint tailwind prettier

---

package-lock.json
package.json
src/components/Navbar.tsx

implemented a responsive navBar

---

package-lock.json
package.json
src/app/globals.css
src/app/page.tsx
src/components/PaymentPage.tsx
src/components/modal/Card-modal.tsx
src/components/modal/Crypto-modal.tsx

**"Implemented modal components for both crypto and cash payments. Additionally, I noticed that the Tailwind CSS setup was using an older configuration. To align with the latest version, I updated the configuration in the globals.css file located in the app directory.
To ensure Tailwind styling works correctly, you’ll need to remove these lines:
`@tailwind base;  
@tailwind components;  
@tailwind utilities;  
`
and replace them with:
`
https://github.com/user-attachments/assets/e3563730-208e-4cc6-9590-91180599b4d1
`

WIP: Modal/Dialog Component

---

package-lock.json
src/components/EmailVerificationPage.tsx

Closes #32 
- This PR introduces a new email verification UI component that guides users through the email verification process during sign-up.
- Created EmailVerificationPage.tsx inside component with a responsive layout
- Integrated the existing AnimatedGradientBackground.tsx component for visual appeal
- Implemented 6-digit verification code input with basic validation
- Added "Resend Code" functionality for users who didn't receive a verification email
- Added appropriate loading states during form submission
- Clear verification instructions and email display
- Accessible input fields with proper labeling
- Mobile-responsive design that maintains functionality across devices
This implementation satisfies all acceptance criteria for the email verification flow, providing users with …

Email Verification UI Implementation

---

src/app/api/courses/auth/signup/page.tsx
src/components/ui/checkbox.tsx
src/components/ui/label.tsx
src/components/ui/progress.tsx
src/components/ui/separator.tsx

This PR introduces the implementation of a signup form with validation for the following fields:
Name
Email
Password
Password Confirmation
Validation Rules:
Name: Required field.
Email: Must be a valid email format.
Password: Required and must meet minimum length criteria (e.g., 8 characters).
Password Confirmation: Must match the entered password.
Any invalid input is highlighted with an appropriate error message for the user to correct. This ensures a more user-friendly and secure signup experience.
Testing:
Ensure that all form fields are properly validated and error messages are displayed when inputs are incorrect.
Confirm that the form can be successfully submitted when all inputs are valid.

implemented singup form with validation for name, email, password

---

package-lock.json
package.json
src/app/layout.tsx
src/app/page.tsx
src/app/password-reset.tsx

This PR implements a password reset request form as described in this issue #31. The form includes:
- Email input field
- Submit button
- Confirmation message upon submission
- Animated gradient background (AnimatedGradientBackground component)
1. New Page:
- Created `/password-reset` route with a form `(app/password-reset.tsx)`.
2. Form Logic:
- Uses React state to handle submission and confirmation.
- Validates email input.
3. Styling:
- Follows existing Tailwind CSS conventions.
- Responsive design for mobile/desktop.
4. Background Integration:
- Uses `AnimatedGradientBackground` component for page background.
Review the changes and provide feedback

Password reset form

---

package-lock.json
src/components/checkout-modal.tsx

This PR implements the checkout and payment ui for course purchases
Closes #44 
N/A
N/A
N/A

add checkout modal component for course purchases

---

src/components/ui/input.tsx

Title
Resolve Issue #46: Implement Notifications and Messaging UI
Description
This pull request addresses [Issue #46](https://github.com/StarkMindsHQ/StrellerMinds-Frontend/issues/46) by creating a fully functional user interface for the notification system and messaging functionality in the StrellerMinds frontend. The implementation allows users to receive updates about courses and forum activity, communicate with instructors and learners, and manage their notification preferences. The UI is responsive, includes real-time indicators, and meets all specified acceptance criteria.

feat: implement notification and messaging ui

---

src/app/dashboard/page.tsx

**Description:**
This PR introduces a responsive hamburger menu for mobile devices. The menu is designed to display navigation links when clicked, enhancing the user experience on smaller screens. 
**Changes:**
- Added a hamburger icon for mobile viewports.
- Created functionality for opening and closing the menu on click.
- Implemented styling to ensure the menu is hidden by default and only displayed when triggered.
- Ensured the menu is responsive and works seamlessly on various mobile viewports.
**Acceptance Criteria:**
- The hamburger menu icon is visible on mobile viewports.
- Clicking the hamburger menu toggles the visibility of the navigation links.
- The menu closes when the user clicks on any link or the icon again.
- The design remains consistent across different mobile devices …

Implement-Mobile-Navigation

---

src/app/page.tsx
src/app/settings/page.tsx
src/app/settings/profile/profile.tsx
src/components/Footer.tsx

This PR modernizes the footer component with a cleaner, more compact design that enhances user experience while maintaining brand consistency.
- **Removed diagonal cut** for a cleaner, more professional appearance
- **Reduced footer height** by 40% through optimized spacing and layout
- **Enhanced visual appeal** with glassmorphism effects and smooth animations
- **Improved alignment** with responsive grid system and consistent spacing
- **Modernized color scheme** using brand colors (#5c0f49 purple, #ffcc00 yellow)
- **Streamlined content organization** for better readability
- Optimized CSS classes for better performance
- Enhanced responsive behavior across all screen sizes
- Improved accessibility with proper ARIA labels
- Consistent hover states and transitions
- Reduced component …

feat: Implement Student Settings Page Layout

---

src/app/not-found.tsx

Closes #76 
This PR adds a 404 page not found whenever the user navigates to a non existent page, with consistent styling with the page.

feat: page not found with proper routing

---

Skeleton-Impl-Guide.md
src/app/code-playground/loading.tsx
src/app/courses/loading.tsx
src/app/dashboard/loading.tsx
src/app/globals.css
src/components/FeaturedCoursesWithLoading.tsx
src/components/skeleton/CodePlaygroundSkeleton.tsx
src/components/skeleton/CourseCardSkeleton.tsx
src/components/skeleton/DashboardSkeleton.tsx
src/components/skeleton/FeatureCardSkeleton.tsx
src/components/skeleton/HeroSkeleton.tsx
src/components/skeleton/TestimonialSkeleton.tsx
src/components/skeleton/index.tsx
src/components/ui/skeleton.tsx
src/hooks/useLoading.ts
tailwind.config.cjs

Closes #71 
This PR adds skeleton components to every page and specific hooks for easier implementation. Also, there is a file explaining in-depth the implementation and how to use it for other pages.

feat: add skeletons

---

package-lock.json
package.json
src/app/courses/page.tsx
src/components/CourseCard.tsx
src/components/FeaturedCourses.tsx
src/lib/course-data.ts

Closes #69 
This PR refactors the course component card to stay consistent across the whole courses. This is how the course component card ends up looking.

feat: refactor course component card

---

src/components/ui/toast.tsx
src/components/ui/toaster.tsx
src/contexts/use-toast.ts

closes #73 
This PR introduces a `ToastContext` and `Toast` component that allows feedback messages to be displayed from anywhere in the application. The toast system improves user experience by providing clear and timely notifications.
**Implementation Details:**
* Created a `ToastContext` to manage toast state globally.
* Added a `Toast` component that renders notifications in the **top-right corner**.
* Configured auto-dismiss functionality so each toast disappears after **3 seconds**.
* Implemented support for multiple toast types:
* ✅ Success
* ❌ Error
* ℹ️ Info
**Acceptance Criteria:**
* Toast appears in the **top-right corner** of the screen.
* Toasts automatically dismiss after **3 seconds**.
* Toast supports **success, error, and info** types.
**Notes:**
This PR sets up the …

Add ToastContext and Toast component for global feedback messages

---

.eslintrc.js
.eslintrc.json
package-lock.json
package.json
prettier.config.js
src/app/login/page.tsx
src/app/password-reset.tsx
src/app/register/page.tsx
src/components/CourseService.ts
src/components/LoginForm.tsx
src/components/NotificationPreferences.tsx
src/components/PaymentPage.tsx
src/lib/logger.ts
tsconfig.json

This pull request focuses on standardizing code style, improving error logging, and modernizing configuration files across the project. The most significant changes include migrating ESLint and Prettier configurations to JSON and ESM formats, enforcing stricter linting rules, replacing `console.log`/`console.error` with a custom `logger` for better error handling, and refactoring code for consistency and readability.
**Configuration and Linting Improvements**
* Migrated ESLint configuration from `.eslintrc.js` to `.eslintrc.json`, added `next/typescript` extension, and enforced stricter rules such as banning `console` except for `warn` and `error`.
* Updated Prettier config from CommonJS (`module.exports`) to ESM (`export default`) for compatibility with modern tooling.
* Downgraded …

I removed console.logs from the production code

---

src/components/Navbar.tsx

Reverts StarkMindsHQ/StrellerMinds-Frontend#126

Revert "Fix: Navbar dead code comments"

---

src/components/ui/loading-wrapper.tsx
src/components/ui/loading.tsx

This PR introduces a standardized **loading component and wrapper** to ensure consistent loading states, styling, and accessibility across the app.  
- `Loading` component for displaying loading states (text, animations, or skeletons)  
- `LoadingWrapper` component for consistent async loading patterns  
- Accessibility support: `role="status"` and `aria-live="polite"`  
- Optional loading message for screen readers and UI feedback  
- Standardized layout and styling for all loading states  
- Created files:  
- `src/components/ui/Loading.tsx`  
- `src/components/ui/LoadingWrapper.tsx`  
- will ensure all components follow the same loading pattern and accessibility rules  
closes #98

Standardize Loading State Across Application

---

ELECTIVE_COURSES_DELETE_FEATURE.md
Skeleton-Impl-Guide.md
pnpm-lock.yaml
src/app/dashboard/admin/elective-courses/[id]/page.tsx
src/app/dashboard/admin/elective-courses/page.tsx
src/app/register/page.tsx
src/app/settings/page.tsx
src/app/settings/profile/profile.tsx
src/components/DeleteCourseDialog.tsx
src/components/ElectiveCourseCard.tsx
src/components/ui/input.tsx
src/lib/elective-course-data.ts

- Add DeleteCourseDialog component with confirmation dialog
- Add ElectiveCourseCard component with delete button
- Create admin elective courses list page (/dashboard/admin/elective-courses)
- Create elective course detail page with delete action
- Implement mock delete function with 500ms delay simulation
- Add toast notifications on successful/failed deletion
- Include 5 sample elective courses with full details
- Fix duplicate Input component definition in ui/input.tsx
- Fix typo in import paths (inputt -> input) in register/settings pages
- Add comprehensive documentation in ELECTIVE_COURSES_DELETE_FEATURE.md
All acceptance criteria met:
✅ Delete button on list & detail pages
✅ Show confirmation dialog before deletion
✅ Mock delete updates UI and shows toast
- Closes #149

feat: add delete elective course action (mock delete) 

---

src/components/testimonial.tsx

Fix: Add Keyboard Navigation Support
